### ISSUE TITLE
Comment out post backs 

### ISSUE THREAD

**Issue by garyfeltham** [citypay/citypay-paylink-wordpress#2]
Currently the post back process sends a URL to Paylink to perform a post back. This is performed in runtime however there is no actually real worth or action generated from it. The code itself just returns back a HTTP 200 OK.

Rather than fully remove the functionality it is worth retaining the code and just comment it out from being actioned.
```
$paylink->setRequestConfig(
            $test_mode,
            //  $postback_url, NOOP, reenable if any workflow requires the post back to be enabled
            $success_url,
            $failure_url
        );
```

The postback operation is a NOOP and should advise so. It will in effect never be called by removal from the above. Any future implementation would need to trust and check the JSON call (i.e. using sha256 digests)
```
function cp_paylink_template_redirect_on_postback()
{
    ob_clean();
    // Boilerplate code to be implemented if post backs are required
    header('HTTP/1.1 200 OK');
    exit;
}
```

**Comment by MichaelM5** [comment]
Postback has been commented out and disabled.
If any user wishes to utilise the post back functionality they will need to uncomment the `function cp_paylink_template_redirect_on_postback()` and remove the `empty($postback_url),` from `$paylink->setRequestConfig()` and uncomment `$postback_url,`.
